apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fx9e5a7fd-nodejs 
  janus-idp.io/tekton: fx9e5a7fd-nodejs
  backstage.io/kubernetes-id: fx9e5a7fd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fx9e5a7fd-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml